name: trilingo_translator
description: "Sinhala-Tamil-English Translator Plus - Academic Language Helper for Sri Lankan Students"
publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: ^3.5.3

dependencies:
  flutter:
    sdk: flutter
  
  # UI Components
  cupertino_icons: ^1.0.8
  google_fonts: ^6.1.0
  flutter_svg: ^2.0.9
  
  # State Management
  provider: ^6.1.1
  
  # Storage & Database
  sqflite: ^2.3.0
  shared_preferences: ^2.2.2
  path_provider: ^2.1.1
  
  # Network & HTTP
  http: ^1.1.0
  dio: ^5.3.2
  
  # Audio & Speech
  flutter_tts: ^3.8.5
  speech_to_text: ^6.6.0
  
  # Camera & Image Processing
  camera: ^0.10.5+5
  image_picker: ^1.0.4
  google_mlkit_text_recognition: ^0.10.0
  
  # Permissions
  permission_handler: ^11.0.1
  
  # Utilities
  intl: ^0.19.0
  uuid: ^4.1.0
  
  # Animation
  lottie: ^2.7.0

dev_dependencies:
  flutter_test:
    sdk: flutter

  # The "flutter_lints" package below contains a set of recommended lints to
  # encourage good coding practices. The lint set provided by the package is
  # activated in the `analysis_options.yaml` file located at the root of your
  # package. See that file for information about deactivating specific lint
  # rules and activating additional ones.
  flutter_lints: ^4.0.0

# For information on the generic Dart part of this file, see the
# following page: https://dart.dev/tools/pub/pubspec

# The following section is specific to Flutter packages.
flutter:
  uses-material-design: true
  
  # Assets
  assets:
    - assets/images/
    - assets/data/
    
  # Fonts
  fonts:
    - family: Poppins
      fonts:
        - asset: packages/google_fonts/fonts/poppins/Poppins-Regular.ttf
    - family: NotoSerifSinhala
      fonts:
        - asset: packages/google_fonts/fonts/noto_serif_sinhala/NotoSerifSinhala-Regular.ttf
    - family: NotoSansTamil
      fonts:
        - asset: packages/google_fonts/fonts/noto_sans_tamil/NotoSansTamil-Regular.ttf

  # An image asset can refer to one or more resolution-specific "variants", see
  # https://flutter.dev/to/resolution-aware-images

  # For details regarding adding assets from package dependencies, see
  # https://flutter.dev/to/asset-from-package

  # To add custom fonts to your application, add a fonts section here,
  # in this "flutter" section. Each entry in this list should have a
  # "family" key with the font family name, and a "fonts" key with a
  # list giving the asset and other descriptors for the font. For
  # example:
  # fonts:
  #   - family: Schyler
  #     fonts:
  #       - asset: fonts/Schyler-Regular.ttf
  #       - asset: fonts/Schyler-Italic.ttf
  #         style: italic
  #   - family: Trajan Pro
  #     fonts:
  #       - asset: fonts/TrajanPro.ttf
  #       - asset: fonts/TrajanPro_Bold.ttf
  #         weight: 700
  #
  # For details regarding fonts from package dependencies,
  # see https://flutter.dev/to/font-from-package
